# http://www.jetbrains.com/help/phpstorm/http-client-in-product-code-editor.html
### 记录推广者，重复记录会更新时间
POST http://{{host}}/api/rest/distribution/apply-promoter?_format=json
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "distributor_id": 6
}

###

POST http://{{host}}/api/rest/distribution/apply-for-distributor?_format=json
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "agent": {
     "name": "王哈哈",
     "phone": "15999643277"
  }
}

###

GET http://{{host}}/api/rest/distribution/last-promoter?_format=json
Accept: application/json
Authorization: Basic {{username}} {{password}}

###

POST http://{{host}}/api/rest/distribution/compute-commission-amount?_format=json
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "commerce_product_variation": [1,2,3]
}

###